unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -s escape-time 0
set -g focus-events on
set -g display-time 4000
set -g status-interval 5
set -g status-keys emacs
setw -g aggressive-resize on
set -g history-limit 50000
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

bind '"' split-window -c "#{pane_current_path}"
bind "%" split-window -h -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:Tc"
set -g window-style 'bg=#121212'
set -g window-active-style 'bg=#181818'

set-hook -g after-copy-mode 'set -p cursor-style underline'
set -g @yank_selection_mouse 'clipboard'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @tmux-gruvbox 'dark'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
