#!/bin/bash

offsec_readme() {
    cat <<- EOF
	---
	layout: Post
	format: chall
	title: $1
	date: 2099-01-01
	platform: HackTheBox
	tags: []
	category: []
	---
	# $1
	
	## Recon
	
	\`\`\`bash
	IP=
	nmap -Pn -p- -T4 -vv -oG nmap.grep \$IP; nmap -sVC -Pn -p\$(grep -oP '\d+(?=/open)' nmap.grep | paste -sd "," -) \$IP; 
	
	nmap -sU --min-rate=5000 -p- \$IP
	
	nxc smb "\$IP" -u '' -p '' --generate-hosts-file /tmp/hosts; cat /tmp/hosts >> /etc/hosts
	\`\`\`
	
	## Service Enumeration
	
	### 
	
	EOF
}

defsec_readme() {
    cat <<- EOF
	---
	layout: Post
	format: chall
	title: $1
	date: 2099-01-01
	platform: HackTheBox
	tags: []
	category: []
	---
	# $1
	
	## Scenario
	
	
	
	We are provided with TODO, it contains:
	
	## Tasks
	
	### 
	
	EOF
}

BOX_NAME=$1

if [ -z "$BOX_NAME" ]; then
  echo "Usage: $0 <box-name>"
  exit 1
fi

BOX_NAME=$(echo $BOX_NAME | tr ' ' '_' | iconv -f utf-8 -t ascii//TRANSLIT)

PATHS_CHOICES=(
    "1: Labs"
    "2: Sherlocks"
    "3: Acedemy"
    "Or write your own (absolute) path"
)

echo "Choose your path (default: 1):"
for choice in "${PATHS_CHOICES[@]}"; do
    echo "$choice"
done
read -p "> " path_choice
path_choice=${path_choice:-1}

case $path_choice in
    1) TARGET_PATH="$HOME/HTB/HTB-Labs/Machines" ;;
    2) TARGET_PATH="$HOME/HTB/HTB-Labs/Sherlocks" ;;
    3) TARGET_PATH="$HOME/HTB/HTB-Academy" ;;
    *) TARGET_PATH="$path_choice" ;;
esac

if [ ! -d "$TARGET_PATH" ]; then
  echo "The specified path does not exist."
  exit 1
fi

cd $TARGET_PATH
mkdir -p $BOX_NAME/assets

if [[ "$TARGET_PATH" != *"Sherlocks"* ]]; then
    mkdir -p $BOX_NAME/share

    if [ ! -f "$TARGET_PATH/$BOX_NAME/README.md" ]; then
        offsec_readme "$BOX_NAME" > "$TARGET_PATH/$BOX_NAME/README.md"
    fi

    VPN_CHOICES=(
        "1: Labs"
        "2: Academy"
        "3: Release Arena"
        # "4: VIP"
    )
    
    echo "Choose your VPN (default: 2):"
    for choice in "${VPN_CHOICES[@]}"; do
        echo "$choice"
    done
    read -p "> " vpn_choice
    vpn_choice=${vpn_choice:-2}
    
    if [ "$vpn_choice" == "1" ]; then
      VPN_PATH="$HOME/Documents/HTB_NedX.ovpn"
    elif [ "$vpn_choice" == "2" ]; then
      VPN_PATH="$HOME/Documents/HTB_Academy_NedX.ovpn"
    elif [ "$vpn_choice" == "3" ]; then
      VPN_PATH="$HOME/Documents/HTB_Release_Arena_NedX.ovpn"
    # elif [ "$vpn_choice" == "4" ]; then
    #   VPN_PATH="$HOME/Documents/HTB_VIP_NedX.ovpn"
    fi
    
    if [ ! -f "$VPN_PATH" ]; then
      echo "The specified VPN file does not exist."
      exit 1
    fi
    
    CMD="exegol start --vpn \"$VPN_PATH\" -w \"$TARGET_PATH/$BOX_NAME\" -V \"$HOME/Downloads:/workspace/Downloads\" --update-fs $BOX_NAME free"
else
    if [ ! -f "$TARGET_PATH/$BOX_NAME/README.md" ]; then
        defsec_readme "$BOX_NAME" > "$TARGET_PATH/$BOX_NAME/README.md"
    fi

    # --update-fs ?????????
    CMD="exegol start -w \"$TARGET_PATH/$BOX_NAME\" -V \"$HOME/Downloads:/workspace/Downloads\" --update-fs $BOX_NAME free"
fi

echo $CMD
read -p "Press [Enter] to start the box..."
eval $CMD
